export var Lang = {
    en: {
        room_name: 'Room name',
        share_location: 'You are sharing your location.',
        not_share_location: 'You are not sharing your location.',
        online_users: 'online users',
        about_us: 'About Us',
        out_room: 'Out Room',
        alert: 'Alert',
        quit_msg: 'Do you want to quit?',
        cancel: 'Cancel',
        ok: 'Ok',
        login: 'Log-In',
        register: 'Register',
        login_room_name: 'Room Name',
        password: 'Password',
        confirm_pass: 'Re-Write Password',
        btn_register: 'Register',
        login_about_us: 'About-us',
        signin: 'Sign In',
        language: 'Language',
        say_something: 'Say something!'
    },
    tur: {
        room_name: 'Grup',
        share_location: 'Lokasyon bilgisi paylaşılıyor!',
        not_share_location: 'Lokasyon bilgisi gizlendi.',
        online_users: 'Katılımcı sayısı',
        about_us: 'Hakkımızda',
        out_room: 'Gruptan çık',
        alert: 'Dikkat',
        quit_msg: 'Gruptan çıkarsanız mesaj ve konum bilgisi paylaşamazsınız.',
        cancel: 'İptal',
        ok: 'Tamam',
        login: 'Giriş yap',
        register: 'Yeni Grup',
        login_room_name: 'Grup ismi',
        password: 'Şifre',
        confirm_pass: 'Şifreni onayla',
        btn_register: 'Oluştur',
        login_about_us: 'Hakkımızda',
        signin: 'Giriş yap',
        language: 'Dil',
        say_something: 'Bir mesaj yaz!'
    }
}
